#!/bin/bash

. /etc/os-release

case $ID in
  debian | ubuntu)
	sudo apt install -y neovim git alacritty tmux xclip curl fontconfig build-essential unzip zsh yadm
    ;;

  arch)
	  sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
	  yay -S bitwarden google-chrome ungoogled-chromium firefox zen-browser-bin discord alacritty ghostty yadm neovim tmux visual-studio-code-bin xclip curl fontconfig base-devel unzip zsh update-grub less noto-fonts noto-fonts-cjk noto-fonts-emoji obsidian git-delta flameshot corepdf dragon gwenview
    ;;

  *) echo "This is an unknown distribution."
      ;;
esac

# Zsh
chsh -s $(which zsh)

# Zap
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 -k

# Get Nerd Fonts
curl -fsSL https://raw.githubusercontent.com/getnf/getnf/main/install.sh | bash

# Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Use SSH
yadm remote set-url origin "git@github.com:stonespren/.dotfiles.git"

# Grub Theme
git clone https://github.com/HeinrichZurHorstMeyer/Framework-Grub-Theme.git
sudo cp -r Framework-Grub-Theme/Framework /boot/grub/themes/
sudo bash -c 'echo "GRUB_THEME=\"/boot/grub/themes/Framework/theme.txt\"" >> /etc/default/grub'
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo update-grub
rm -rf Framework-Grub-Theme

# Pnpm
curl -fsSL https://get.pnpm.io/install.sh | sh -

/home/$USER/.config/custom/link-arch.sh

echo "Restart your computer"
