#!/bin/bash

# Install packages
sudo apt install -y neovim git alacritty tmux xclip curl fontconfig build-essential unzip zsh

# Zsh
chsh -s $(which zsh)

# Zap
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 -k

# Get Nerd Fonts
curl -fsSL https://raw.githubusercontent.com/getnf/getnf/main/install.sh | bash

# Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Use SSH
yadm remote set-url origin "git@github.com:stonespren/.dotfiles.git"

echo "Restart your computer"
