auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Touch sensor
    }
}

label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 16
    font_family = $font

    position = 0, 40
    halign = center
    valign = center
}
